title: Pedro Tavares (ordep.dev)
email: pedrotavares.dev@gmail.com
description: Thoughts from @ordepdev
baseurl: "/"
url: "https://ordep.dev"
permalink: /posts/:title
twitter_username: ordepdev
github_username: ordepdev
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-toc
toc:
  ordered_list: true
collections:
  - now
