title: Thoughts from @ordepdev
email: pedrotavares.dev@gmail.com
description: >
  I am a seasoned software engineer with a passion for creating innovative and 
  intuitive technology solutions. With over 10 years of experience in the industry, 
  I have a deep understanding of the software development life cycle and a track record 
  of delivering high-quality products on time and within budget. If you're looking for a 
  results-driven software developer with expertise around distributed systems, JVM and the 
  BEAM please feel free to connect!
baseurl: "/"
url: "https://ordep.dev"
permalink: /posts/:title
twitter_username: ordepdev
github_username: ordepdev
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-toc
toc:
  ordered_list: true
collections:
  - now
