title: Blog about software
email: pedrotavares.dev@gmail.com
description: >
  I’m a passionate Software Engineer with interests around automated workflows,
  microservices, test-driven development, design patterns, and databases. Currently,
  I work at Jumia Services, the leading e-commerce fulfillment and delivery in Africa.
  If you can’t find me building software, I bet you’ll find me playing videogames or
  surfing waves in Portugal’s Northern Coast.
baseurl: "/"
url: "ordep.dev"
permalink: /posts/:title
twitter_username: ordepdev
github_username:  ordepdev

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
